### ISSUE TITLE
chore: Add codecov.yml Configuration File

### ISSUE THREAD

**Issue by jakub-k-slys** [jakub-k-slys/substack-api#18]
Goal: Configure Codecov behavior for this repository using a codecov.yml file to control thresholds, comment layout, ignored folders, and rounding behavior.

✅ Tasks
	•	Create a file named codecov.yml in the .github directory 
	•	Add the following configuration content:

```
coverage:
    status:
        patch: true
        project:
            default:
                target: auto
                threshold: 10%
    range: 60..80
    round: down
    precision: 2
ignore:
    - docs
comment:
    layout: diff, files
```

📌 What This Configuration Does
	•	🎯 Sets project coverage to be evaluated automatically with a ±10% threshold
	•	📉 Coverage range: 60% to 80%
	•	🔢 Rounds down and limits to 2 decimal places
	•	🙈 Ignores the docs directory from coverage reports
	•	💬 Controls Codecov comments layout to show diffs and per-file coverage
